### ISSUE TITLE
Contributor roles

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#2]
* Contributors can add to collections but they can't view items as collections (this will be really helpful––they’ve been making a lot of errors that could be fixed if they can check the collections)

* It appears that anyone who signs up for an account automatically has the ability to upload files even before I assign them contributor privileges

**Comment by scande3** [comment]
Issue 1: should be fixed in the next pull now. Question: should contributors only see files they have uploaded? Or all files?

Issue 2: That should have been fixed some time ago. Is it still the case they are able to do so?

**Comment by kjrawson** [comment]
They can have access to see all files, but should only be able to edit the ones that they have uploaded. The second part I haven't checked in a few weeks––sorry if that was already completed.

**Comment by scande3** [comment]
Rick just pulled down the changes. Issue 1 should now be live (but will need to add a check to stop them from editing files).

Additionally, the "regenerate thumbnail" action on the drop down next to the list of files should now work for those few items missing thumbnails.

**Comment by kjrawson** [comment]
Great, thanks!

**Comment by kjrawson** [comment]
The permissions for contributors still isn't working properly. One student was able to edit records that I had uploaded. Also, contributors are able to see all records in the file list, but not in collections views––can that be changed?

**Comment by kjrawson** [comment]
Also, contributors can't view thumbnails from other people's records
