### ISSUE TITLE
Error message for creating new institution

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#83]
When I try to add a new institution, I am getting an error message. Thanks!

**Comment by scande3** [comment]
Fixed in commits 5f404489ffcb4982feeac974ff761837cafaf382 and 5dd5371afaec2fc84d1c65cbb0217128158c1f5b .

Can you verify that it is so? Thanks!

**Comment by kjrawson** [comment]
I was able to add a new institution, but I still cannot create new collections. I am able to open the link and add information, but I get an error when I try to create the collection.

**Comment by scande3** [comment]
Fixed what might have been the issue if you can verify. But leave this issue open for one more commit as while fixed, I want to do some cleanup of code logic this weekend and add a few unit tests to catch future issues. Commit 2abb316a1e0898b0af18aa41bd6fab703b6f3f72

**Comment by kjrawson** [comment]
Yes, it's working fine now. Thanks!

**Comment by kjrawson** [comment]
I am guessing this is all set now? Thanks!
